### ISSUE TITLE
blockelement vertical

### ISSUE THREAD

**Issue by maxinecaulfield** [maxinecaulfield/Notes#2]
```css
html, body{ height: 100%;margin:0; padding:0; }
```
 
方法一
子元素绝对定位，top50%，再设置负边距为子元素高度的一半

```css
#outbox{
    position: relative;
}
#content {
    position: absolute;
    top: 50%;
    height: 240px;
    margin-top: -120px; /* negative half of the height */
}
```

优点： 
适用于所有浏览器 
不需要嵌套标签
缺点： 
没有足够空间时，content 会消失
（类似div 在 body 内，当用户缩小浏览器窗口，滚动条不出现的情况）

方法二
在content上面插入一个div设置高度50%，margin-bottom为content一半的高度
```css
#floater {
    height: 50%;
    margin-bottom: -120px;
}
#content {
    height: 240px;
}
```
优点： 
适用于所有浏览器 
没有足够空间时(例如：窗口缩小) content 不会被截断，滚动条出现
缺点：
暂无

方法三
利用表格 vertical-align property 属性
```html
<div id="wrapper">  
    <div id="cell">
        <div class="content">Content goes here</div>
    </div>
</div>  
```
```css
#wrapper {
    display: table;
}
#cell {
    display: table-cell;
    vertical-align: middle;
}
```
优点： 
content 可以动态改变高度(不需在 CSS 中定义)。当 wrapper 里没有足够空间时， content 不会被截断
缺点： 
Internet Explorer(甚至 IE8 beta)中无效
